### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til statistikk på trafikk i API`et

### ISSUE THREAD

**Issue by BR-Svein** [datautvikling/behov#5]
Som: Produkteier
Ønsker jeg å: kunne angi periode for å få statistikk på antall oppslag i API`et
Slik at: vi kan ha oversikt over trafikken i tjenesten.

Relatert til epos: Informasjonsforvaltning/behov#180 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi: Viktig

**Comment by sskagemo** [comment]
Implementert tre ulike statistikkfunksjoner: Antall forespørsler for hhv IP-adresser forespørslene kommer fra (IP-adressene er anonymiserte), hvilke metoder som er brukt, og organisasjonsnummer det er forespurt om regnskap for. Tidsperiode kan spesifiseres, på formatet YYYY-MM-DD. Uten angivelse av tidsperiode er det ingen begrensning, m.a.o. fra tjenesten startet i januar 2021.
