### ISSUE TITLE
[BRUKERHISTORIE] Importere begrepsbeskrivelse som CSV-format til registreringsløsningen

### ISSUE THREAD

**Issue by marittor** [datautvikling/behov#53]
Som: skrivebruker
Gitt at jeg står på oversiktsside til Felles begrepskatalog registreringsløsning
Ønsker jeg å: kunne importere begreper på CSV-format
Slik at: Jeg kan ta inn ei hel liste over begreper der hvert begrep registreres for seg
Og slik at: jeg kan jobbe videre med med min virksomhets begreper med hensikt å publisere dem fra registreringsløsningen

Se mer informasjon i behovsprosjektet: https://github.com/Informasjonsforvaltning/behov/issues/344 

Akseptansekriterier: 
Importen må ivareta at innholdet kan være på flere språk og målformer:
o	Feilmeldinger i CSV skal angi hvilken rad og kolonne som har feilet
o	Feil i heading skal gjenkjennes
o	Følgende feil i data skal gi feilmelding
	Ugyldig epost input
	Ugyldig lenke
	Manglende utfylling av obligatoriske felter (anbefalt term og definisjon)

**Comment by sskagemo** [comment]
Forslag:
- starte med back-end -- hvilken komponent er det? Kildekoden?
- legge til API-funksjon for å POSTe Excel-ark iht mal. Foreslå detaljer om API-kallet
- Lese innholdet i mal-en, evt feilmeldinger, og opprette tilsvarende begrep i katalogen

**Comment by marittor** [comment]
Brukerhistorien levert og produksjonssatt.
